apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  labels:
    app: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      pod-label: plex
  template:
    metadata:
      labels:
        pod-label: plex
    spec:
      containers:
        - name: plex
          image: lscr.io/linuxserver/plex:latest
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /plexmedia
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: VERSION
              value: docker
      volumes:
      - name: config
        persistentVolumeClaim:
         claimName: plex-pvc
      - name: media
        persistentVolumeClaim:
         claimName: plex-media