apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-smb
spec:
  capacity:
    storage: 1000000Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=1001
    - gid=1001
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino  # required to prevent data corruption
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: 9912  # make sure it's a unique id in the cluster
    volumeAttributes:
      source: "//10.10.0.151/cloud/media"
    nodeStageSecretRef:
      name: smbcreds
      namespace: default