apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
  labels:
    app: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      pod-label: minecraft
  template:
    metadata:
      labels:
        pod-label: minecraft
    spec:
      containers:
        - name: minecraft
          image: itzg/minecraft-server:2022.6.0-java17-jdk
          volumeMounts:
            - name: storage
              mountPath: /data
          env:
            - name: EULA
              value: "true"
            - name: TYPE
              value: "PAPER"
            - name: PAPER_DOWNLOAD_URL
              value: "https://api.papermc.io/v2/projects/paper/versions/1.18.2/builds/372/downloads/paper-1.18.2-372.jar"
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: minecraft-pvc
