apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
  labels:
    app: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      pod-label: minecraft
  template:
    metadata:
      labels:
        pod-label: minecraft
    spec:
      containers:
        - name: minecraft
          image: itzg/minecraft-server
          volumeMounts:
            - name: storage
              mountPath: /data
          env:
            - name: EULA
              value: "true"
            - name: TYPE
              value: "PAPER"
            - name: PAPERBUILD
              value: "372"
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: minecraft-pvc
