apiVersion: v1
kind: Service
metadata:
  name: minecraft-service
spec:
  selector:
    app: minecraft
  ports:
    - protocol: TCP
      port: 25565
  env:
    - name: EULA
      value: true
  type: LoadBalancer