apiVersion: v1
kind: Service
metadata:
  name: minecraft-service
  labels:
    app: minecraft
spec:
  selector:
    pod-label: minecraft
  ports:
    - protocol: TCP
      port: 25565
  type: LoadBalancer